spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
      location: ${java.io.tmpdir}
      enabled: true